import XCTest
@testable import auto_proxy_patcher

final class PatchBundleIdTests: XCTestCase {

    private var tempDir: URL!

    override func setUp() {
        super.setUp()
        tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("bundleid-tests-\(UUID().uuidString)")
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    }

    override func tearDown() {
        try? FileManager.default.removeItem(at: tempDir)
        super.tearDown()
    }

    private func createMockAppDir(bundleId: String = "com.example.app") throws -> URL {
        let appDir = tempDir.appendingPathComponent("Test.app")
        try FileManager.default.createDirectory(at: appDir, withIntermediateDirectories: true)

        let plist: [String: Any] = [
            "CFBundleIdentifier": bundleId,
            "CFBundleExecutable": "Test",
            "CFBundleName": "Test",
        ]
        let data = try PropertyListSerialization.data(fromPropertyList: plist, format: .xml, options: 0)
        try data.write(to: appDir.appendingPathComponent("Info.plist"))

        return appDir
    }

    func testAutoGeneratedBundleId() throws {
        let appDir = try createMockAppDir(bundleId: "com.example.app")

        try PatchBundleIdStep.execute(appDir: appDir, bundleId: nil, keepBundleId: false)

        let plist = PatchBundleIdStep.readPlist(at: appDir.appendingPathComponent("Info.plist"))!
        XCTAssertEqual(plist["CFBundleIdentifier"] as? String, "com.patched.com.example.app")
    }

    func testCustomBundleId() throws {
        let appDir = try createMockAppDir(bundleId: "com.example.app")

        try PatchBundleIdStep.execute(appDir: appDir, bundleId: "com.custom.id", keepBundleId: false)

        let plist = PatchBundleIdStep.readPlist(at: appDir.appendingPathComponent("Info.plist"))!
        XCTAssertEqual(plist["CFBundleIdentifier"] as? String, "com.custom.id")
    }

    func testKeepBundleId() throws {
        let appDir = try createMockAppDir(bundleId: "com.example.app")

        try PatchBundleIdStep.execute(appDir: appDir, bundleId: nil, keepBundleId: true)

        let plist = PatchBundleIdStep.readPlist(at: appDir.appendingPathComponent("Info.plist"))!
        XCTAssertEqual(plist["CFBundleIdentifier"] as? String, "com.example.app")
    }

    func testPreservesOtherPlistKeys() throws {
        let appDir = try createMockAppDir(bundleId: "com.example.app")

        try PatchBundleIdStep.execute(appDir: appDir, bundleId: "com.new.id", keepBundleId: false)

        let plist = PatchBundleIdStep.readPlist(at: appDir.appendingPathComponent("Info.plist"))!
        XCTAssertEqual(plist["CFBundleExecutable"] as? String, "Test")
        XCTAssertEqual(plist["CFBundleName"] as? String, "Test")
    }
}
