name: AutoProxyExample
options:
  bundleIdPrefix: com.guthyerrz.autoproxy
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "16.0"
settings:
  SWIFT_VERSION: "5.9"
  ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: YES
  ENABLE_USER_SCRIPT_SANDBOXING: NO
  SWIFT_EMIT_LOC_STRINGS: YES
targets:
  AutoProxyExample:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      INFOPLIST_FILE: Sources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.guthyerrz.autoproxy.example
    scheme:
      testTargets:
        - AutoProxyTests
  AutoProxyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ../Tests/AutoProxyTests
    dependencies:
      - target: AutoProxyExample
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.guthyerrz.autoproxy.tests
      GENERATE_INFOPLIST_FILE: YES
  PatcherTestApp:
    type: application
    platform: iOS
    sources:
      - PatcherTestSources
    settings:
      INFOPLIST_FILE: PatcherTestSources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.guthyerrz.autoproxy.patchertest
